# Generated by Django 5.2.7 on 2026-02-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=25)),
                ('raqam', models.IntegerField(default=0)),
                ('yosh', models.IntegerField(default=0)),
                ('address', models.TextField(blank=True, null=True)),
                ('raqam2', models.IntegerField(default=0)),
                ('dokon_nomi', models.CharField(max_length=25)),
            ],
        ),
    ]
